package com.baseprovider.config

import com.lagradost.cloudstream3.TvType

val ANICHIN = GLOBAL_CONFIG.copy(
    id = "Anichin",
    name = "Anichin",
    mainUrl = "https://anichin.cafe",
    seriesUrl = null,
    searchUrl = null,
    lang = "id",
    supportedTypes = setOf(TvType.Anime, TvType.AnimeMovie, TvType.TvSeries),
    searchPathPattern = "{baseUrl}/page/{page}/?s={query}",
    mainPagePathPattern = "{baseUrl}/{data}{page}",
    moviePathSegment = "-movie-",
    tvPathSegment = "/anime/",
    episodeDataUrlPattern = "{url}",
    searchPageLimit = 3,
    reverseEpisodes = true,
    isJsonSearch = false,
    searchJsonRoot = "data",
    searchJsonTitle = "title",
    searchJsonHref = "slug",
    searchJsonPoster = "poster",
    searchJsonPosterPrefix = "",
    searchJsonType = "type",
    useDocumentLarge = false,
    cacheTtlMinutes = 5L,
    isHorizontal = false,
    refererPlayerMode = "current_url",
    iframeSelectors = "iframe",
    globalHeaders = mapOf(
        "User-Agent" to "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        "Accept-Language" to "id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7"
    ),
    mainPageLists = listOf(
        "seri/?status=&type=&order=popular&page=" to "Popular Donghua",
        "seri/?status=&type=&order=update&page=" to "Recently Updated",
        "seri/?sub=&order=latest&page=" to "Latest Added",
        "seri/?status=ongoing&type=&order=update&page=" to "Ongoing",
        "seri/?status=completed&type=&order=update&page=" to "Completed"
    ),
    dubKeyword = "dub",
    ongoingKeyword = "Ongoing",
    episodeKeyword = "Episode",
    seriesKeyword = "Series",
    comingSoonKeywords = "Coming Soon",
    searchItems = "div.listupd > article",
    searchTitle = "div.bsx h2, .tt, a[title]",
    searchHref = "a",
    searchPoster = "div.bsx img, .ts-post-image, .wp-post-image",
    searchRating = ".rtng, .score, .rating",
    searchEpText = ".eps span, .epx, .bt span.epx",
    loadTitle = "h1.entry-title, h1.title, .entry-title h1",
    loadPoster = "div.thumb img, .ts-post-image, .wp-post-image",
    loadBanner = "",
    loadDesc = "div.description, .entry-content, .desc",
    loadInfoBox = ".spe",
    loadTags = "",
    loadRating = "",
    loadStatus = "",
    loadQuality = "",
    loadTrailer = "",
    loadRecommend = ".listupd article, .listupd .bsx, .related-post article, .relat article",
    episodeItems = ".eplister li",
    episodeHref = ".eplister li > a",
    episodeTitle = ".epl-title",
    episodeNum = ".epl-num",
    episodeDesc = "",
    episodeTime = "",
    linkOptions = "option[data-index], option[value]",
    downloadItems = "",
    actorItems = "",
    actorName = "",
    watchButtons = ".play-button, .watch-now, .btn-watch",
    seasonContainer = ".tvseason, #season-data",
    imdbExternal = "a[href*='imdb.com/title/']",
    tmdbExternal = "a[href*='themoviedb.org/']",
    iframeTag = "iframe",
    followLinkSelector = "",
    seasonDataSelector = "",
    ajaxPlayerUrl = "",
    selectorJsonData = "",
    attrImage = listOf("data-original", "data-src", "data-lazy-src", "data-litespeed-src", "src", "content"),
    attrHref = listOf("href"),
    attrValue = listOf("value", "data-index", "data-id", "data-url", "data-link", "data-litespeed-src"),
    iframeSources = listOf("src", "data-src", "data-link", "data-litespeed-src"),
    hrefCleanRegex = "",
    hrefCleanReplace = "",
    yearSelector = "",
    yearExtractorRegex = "",
)
