package com.baseprovider.config

import com.lagradost.cloudstream3.TvType

val ANIMASU = GLOBAL_CONFIG.copy(
    id = "Animasu",
    name = "Animasu",
    mainUrl = "https://animasu.ink",
    mirrorUrls = listOf("https://v1.animasu.work"),
    seriesUrl = null,
    searchUrl = null,
    lang = "id",
    supportedTypes = setOf(TvType.Anime, TvType.AnimeMovie, TvType.OVA),
    searchPathPattern = "{baseUrl}/?s={query}",
    mainPagePathPattern = "{baseUrl}/{data}{page}",
    moviePathSegment = "/movie/",
    tvPathSegment = "/anime/",
    episodeDataUrlPattern = "{url}",
    searchPageLimit = 1,
    reverseEpisodes = true,
    isJsonSearch = false,
    searchJsonRoot = "data",
    searchJsonTitle = "title",
    searchJsonHref = "slug",
    searchJsonPoster = "poster",
    searchJsonPosterPrefix = "",
    searchJsonType = "type",
    useDocumentLarge = false,
    cacheTtlMinutes = 5L,
    isHorizontal = false,
    refererPlayerMode = "current_url",
    iframeSelectors = "iframe",
    globalHeaders = mapOf(
        "User-Agent" to "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        "Accept-Language" to "id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7"
    ),
    mainPageLists = listOf(
        "page/" to "Terbaru",
        "series/?status=&type=&order=update&page=" to "Series Update",
        "series/?status=&type=&order=popular&page=" to "Series Populer",
        "anime/page/" to "Anime",
        "donghua/page/" to "Donghua"
    ),
    dubKeyword = "dub",
    ongoingKeyword = "Ongoing",
    episodeKeyword = "Episode",
    seriesKeyword = "Series",
    comingSoonKeywords = "Coming Soon",
    searchItems = "div.listupd .bsx, div.listupd .bs, div.listupd article.bs",
    searchTitle = "div.tt",
    searchHref = "a",
    searchPoster = "div.limit img, img[data-src], .thumb img",
    searchRating = "",
    searchEpText = "span.epx",
    loadTitle = "h1.entry-title, h1[itemprop=headline], div.infox h1",
    loadPoster = "div.thumb img, .ts-post-image, div.bigcontent img",
    loadBanner = "",
    loadDesc = "p.mindesc, div.sinopsis, .desc",
    loadInfoBox = "div.infox div.spe",
    loadTags = "div.genxed a",
    loadRating = "",
    loadStatus = "span:contains(Status:)",
    loadTrailer = "",
    loadRecommend = ".listupd article, .listupd .bsx, .related-post article, .relat article",
    episodeItems = ".eplister ul > li",
    episodeHref = "a",
    episodeTitle = "a",
    episodeNum = ".ep-num, .epl-num",
    episodeDesc = "",
    episodeTime = "",
    linkOptions = "select.mirror option",
    downloadItems = "",
    actorItems = "",
    actorName = "",
    watchButtons = ".play-button, .watch-now, .btn-watch",
    seasonContainer = ".tvseason, #season-data",
    imdbExternal = "a[href*='imdb.com/title/']",
    tmdbExternal = "a[href*='themoviedb.org/']",
    iframeTag = "iframe",
    followLinkSelector = "",
    ajaxPlayerUrl = "",
    selectorJsonData = "",
    attrImage = listOf("data-original", "data-src", "data-lazy-src", "data-litespeed-src", "src", "content"),
    attrHref = listOf("href"),
    attrValue = listOf("value", "data-index", "data-id", "data-url", "data-link", "data-litespeed-src"),
    iframeSources = listOf("src", "data-src", "data-link", "data-litespeed-src"),
    hrefCleanRegex = "",
    hrefCleanReplace = "",
    yearSelector = "",
    yearExtractorRegex = "",
)
