package com.baseprovider.config

import com.lagradost.cloudstream3.TvType

val DUTAMOVIE21 = GLOBAL_CONFIG.copy(
    id = "Dutamovie21",
    name = "Dutamovie21",
    mainUrl = "https://simplycufflinks.com",
    seriesUrl = null,
    searchUrl = null,
    lang = "id",
    supportedTypes = setOf(TvType.Movie, TvType.TvSeries, TvType.AsianDrama, TvType.Anime),
    searchPathPattern = "{baseUrl}/page/{page}/?s={query}",
    mainPagePathPattern = "{baseUrl}/{data}/page/{page}",
    moviePathSegment = "/movie/",
    tvPathSegment = "/series/",
    episodeDataUrlPattern = "{url}",
    searchPageLimit = 2,
    reverseEpisodes = false,
    isJsonSearch = false,
    searchJsonRoot = "data",
    searchJsonTitle = "title",
    searchJsonHref = "slug",
    searchJsonPoster = "poster",
    searchJsonPosterPrefix = "",
    searchJsonType = "type",
    useDocumentLarge = true,
    cacheTtlMinutes = 5L,
    isHorizontal = false,
    refererPlayerMode = "series_url",
    iframeSelectors = "div.embed-container iframe, .gmr-embed-responsive iframe, iframe",
    globalHeaders = mapOf(
        "User-Agent" to "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        "Accept-Language" to "id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7"
    ),
    mainPageLists = listOf(
        "category/box-office" to "Box Office",
        "category/serial-tv" to "TV Series",
        "action" to "Action",
        "adventure" to "Adventure",
        "animation" to "Animation",
        "comedy" to "Comedy",
        "crime" to "Crime",
        "drama" to "Drama",
        "fantasy" to "Fantasy",
        "horror" to "Horror",
        "mystery" to "Mystery",
        "romance" to "Romance",
        "science-fiction" to "Sci-Fi",
        "thriller" to "Thriller",
        "country/china" to "China",
        "country/indonesia" to "Indonesia",
        "country/korea" to "Korea",
        "country/philippines" to "Philippines",
        "country/thailand" to "Thailand"
    ),
    dubKeyword = "dub",
    ongoingKeyword = "Ongoing",
    episodeKeyword = "Episode",
    seriesKeyword = "Series",
    comingSoonKeywords = "Coming Soon",
    searchItems = "article.item, article.item-infinite, div#gmr-main-load article",
    searchTitle = "h2.entry-title a, .entry-title a",
    searchHref = "a",
    searchPoster = "div.content-thumbnail img, img[data-src], img[src]",
    searchRating = "",
    searchEpText = "",
    loadTitle = "h1.entry-title, div.movie-info h1",
    loadPoster = "meta[property=\"og:image\"], div.gmr-movie-data figure img, figure.pull-left img",
    loadBanner = "",
    loadDesc = "div.description, div.entry-content",
    loadInfoBox = "div.content-moviedata",
    loadTags = "div.gmr-moviedata a[rel=\"category tag\"], .gmr-movie-on a",
    loadRating = "div.info-tag strong, .gmr-rating-item",
    loadStatus = "",
    loadQuality = "",
    loadTrailer = ".gmr-trailer-popup",
    loadRecommend = "div.gmr-grid article, .gmr-related-title + .row article",
    episodeItems = ".eplister li",
    episodeHref = "a",
    episodeTitle = "a, .ep-name, .epl-title",
    episodeNum = ".ep-num, .epl-num",
    episodeDesc = "",
    episodeTime = "",
    linkOptions = "ul.muvipro-player-tabs li a",
    downloadItems = "",
    actorItems = "div.movie-cast div.cast-item, .movie-info .cast-item, .gmr-moviedata span[itemprop=actors]",
    actorName = "span[itemprop=name], .cast-name, h3",
    watchButtons = ".play-button, .watch-now, .btn-watch",
    seasonContainer = ".tvseason, #season-data",
    imdbExternal = "a[href*='imdb.com/title/']",
    tmdbExternal = "a[href*='themoviedb.org/']",
    iframeTag = "iframe",
    followLinkSelector = "a#openNow, div.links a",
    seasonDataSelector = "",
    ajaxPlayerUrl = "",
    selectorJsonData = "",
    attrImage = listOf("data-original", "data-src", "data-lazy-src", "data-litespeed-src", "src", "content"),
    attrHref = listOf("href"),
    attrValue = listOf("value", "data-index", "data-id", "data-url", "data-link", "data-litespeed-src"),
    iframeSources = listOf("src", "data-src", "data-link", "data-litespeed-src"),
    hrefCleanRegex = "",
    hrefCleanReplace = "",
    yearSelector = "div.movie-info h1",
    yearExtractorRegex = "\\d, (\\d+)",
)
