package com.baseprovider.config

import com.lagradost.cloudstream3.TvType

val LAYARKACA21 = GLOBAL_CONFIG.copy(
    id = "LayarKaca21",
    name = "LayarKaca",
    mainUrl = "https://tv10.lk21official.cc",
    seriesUrl = "https://tv10.lk21official.cc/nontondrama",
    searchUrl = "https://gudangvape.com",
    lang = "id",
    supportedTypes = setOf(TvType.Movie, TvType.TvSeries, TvType.AsianDrama),
    searchPathPattern = "{baseUrl}/?s={query}",
    mainPagePathPattern = "{baseUrl}/{data}{page}",
    moviePathSegment = "/",
    tvPathSegment = "/nontondrama/",
    episodeDataUrlPattern = "{url}",
    searchPageLimit = 1,
    reverseEpisodes = false,
    isJsonSearch = false,
    searchJsonRoot = "data",
    searchJsonTitle = "title",
    searchJsonHref = "slug",
    searchJsonPoster = "poster",
    searchJsonPosterPrefix = "",
    searchJsonType = "type",
    useDocumentLarge = true,
    cacheTtlMinutes = 5L,
    isHorizontal = false,
    refererPlayerMode = "series_url",
    iframeSelectors = "div.embed-container iframe, .gmr-embed-responsive iframe, iframe",
    globalHeaders = mapOf(
        "User-Agent" to "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        "Accept-Language" to "id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7"
    ),
    mainPageLists = listOf(
        "https://tv10.lk21official.cc/populer/page/" to "Film Terpopuler",
        "https://tv10.lk21official.cc/rating/page/" to "Film Berdasarkan IMDb Rating",
        "https://tv10.lk21official.cc/most-commented/page/" to "Film Dengan Komentar Terbanyak",
        "https://series.lk21.de/latest-series" to "Series Terbaru",
        "https://series.lk21.de/series/asian" to "Film Asian Terbaru",
        "https://tv10.lk21official.cc/latest/page/" to "Film Upload Terbaru"
    ),
    dubKeyword = "dub",
    ongoingKeyword = "Ongoing",
    episodeKeyword = "Episode",
    seriesKeyword = "Series",
    comingSoonKeywords = "Coming Soon",
    searchItems = "div.content-main article, div#gmr-main-load article, div.gallery-grid article",
    searchTitle = "h3, h2, a[title]",
    searchHref = "a",
    searchPoster = "div.poster img, img[data-src]",
    searchRating = "",
    searchEpText = "",
    loadTitle = "div.movie-info h1, h1.entry-title",
    loadPoster = "div.movie-info > img, div#movie-poster img, div.movie-info div.poster img, div.poster img",
    loadBanner = "",
    loadDesc = "div.meta-info",
    loadInfoBox = "div.gmr-moviedata",
    loadTags = "div.tag-list span, .gmr-movie-on a",
    loadRating = "div.info-tag strong, .gmr-rating-item",
    loadStatus = "",
    loadTrailer = ".gmr-trailer-popup",
    loadRecommend = "div#gmr-related-load article, div.related-post article",
    episodeItems = ".eplister li",
    episodeHref = "a",
    episodeTitle = "a, .ep-name, .epl-title",
    episodeNum = ".ep-num, .epl-num",
    episodeDesc = "",
    episodeTime = "",
    linkOptions = "ul#player-list > li",
    downloadItems = "",
    actorItems = "div.movie-cast div.cast-item, .movie-info .cast-item, .gmr-moviedata span[itemprop=actors]",
    actorName = "span[itemprop=name], .cast-name, h3",
    watchButtons = ".play-button, .watch-now, .btn-watch",
    seasonContainer = ".tvseason, #season-data",
    imdbExternal = "a[href*='imdb.com/title/']",
    tmdbExternal = "a[href*='themoviedb.org/']",
    iframeTag = "iframe",
    followLinkSelector = "a#openNow, div.links a",
    ajaxPlayerUrl = "https://youlike.lk21.party/index.php",
    selectorJsonData = "script#watch-history-data",
    attrImage = listOf("data-original", "data-src", "data-lazy-src", "data-litespeed-src", "src", "content"),
    attrHref = listOf("href"),
    attrValue = listOf("value", "data-index", "data-id", "data-url", "data-link", "data-litespeed-src"),
    iframeSources = listOf("src", "data-src", "data-link", "data-litespeed-src"),
    hrefCleanRegex = "",
    hrefCleanReplace = "",
    yearSelector = "div.movie-info h1",
    yearExtractorRegex = "\\d, (\\d+)",
)
