package com.baseprovider.config

import com.lagradost.cloudstream3.TvType

val PENCURIMOVIE = GLOBAL_CONFIG.copy(
    id = "Pencurimovie",
    name = "Pencurimovie",
    mainUrl = "https://ww73.pencurimovie.bond",
    seriesUrl = null,
    searchUrl = null,
    lang = "id",
    supportedTypes = setOf(TvType.Movie, TvType.Anime, TvType.Cartoon),
    searchPathPattern = "{baseUrl}/?s={query}",
    mainPagePathPattern = "{baseUrl}/{data}/page/{page}",
    moviePathSegment = "/movies/",
    tvPathSegment = "/series/",
    episodeDataUrlPattern = "{url}",
    searchPageLimit = 2,
    reverseEpisodes = false,
    isJsonSearch = false,
    searchJsonRoot = "data",
    searchJsonTitle = "title",
    searchJsonHref = "slug",
    searchJsonPoster = "poster",
    searchJsonPosterPrefix = "",
    searchJsonType = "type",
    useDocumentLarge = false,
    cacheTtlMinutes = 5L,
    isHorizontal = false,
    refererPlayerMode = "current_url",
    iframeSelectors = "iframe",
    globalHeaders = mapOf(
        "User-Agent" to "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        "Accept-Language" to "id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7"
    ),
    mainPageLists = listOf(
        "movies" to "Latest Movies",
        "series" to "TV Series",
        "most-rating" to "Most Rating Movies",
        "top-imdb" to "Top IMDB Movies"
    ),
    dubKeyword = "dub",
    ongoingKeyword = "Ongoing",
    episodeKeyword = "Episode",
    seriesKeyword = "Series",
    comingSoonKeywords = "Coming Soon",
    searchItems = "div.ml-item",
    searchTitle = "a[oldtitle], a[title]",
    searchHref = "a",
    searchPoster = "a img[data-original], a img[data-src]",
    searchRating = "",
    searchEpText = ".mli-eps",
    loadTitle = "div.mvic-desc h3",
    loadPoster = "div.mvic-thumb img",
    loadBanner = "",
    loadDesc = "div.desc p.f-desc",
    loadInfoBox = "div.mvic-info",
    loadTags = "div.mvic-info p:contains(Genre) a",
    loadRating = "",
    loadStatus = "",
    loadQuality = "",
    loadTrailer = "",
    loadRecommend = ".mlw-related .ml-item, #related-items .ml-item",
    episodeItems = "div.tvseason div.les-content a",
    episodeHref = "a",
    episodeTitle = "a",
    episodeNum = ".ep-num, .epl-num",
    episodeDesc = "",
    episodeTime = "",
    linkOptions = "div.player_nav a, ul.list-server li",
    downloadItems = "",
    actorItems = "",
    actorName = "",
    watchButtons = ".play-button, .watch-now, .btn-watch",
    seasonContainer = ".tvseason, #season-data",
    imdbExternal = "a[href*='imdb.com/title/']",
    tmdbExternal = "a[href*='themoviedb.org/']",
    iframeTag = "iframe",
    followLinkSelector = "",
    seasonDataSelector = "",
    ajaxPlayerUrl = "",
    selectorJsonData = "",
    attrImage = listOf("data-original", "data-src", "data-lazy-src", "data-litespeed-src", "src", "content"),
    attrHref = listOf("href"),
    attrValue = listOf("value", "data-index", "data-id", "data-url", "data-link", "data-litespeed-src"),
    iframeSources = listOf("src", "data-src", "data-link", "data-litespeed-src"),
    hrefCleanRegex = "",
    hrefCleanReplace = "",
    yearSelector = "",
    yearExtractorRegex = "",
)
