package com.baseprovider.config

import com.lagradost.cloudstream3.TvType

val SAMEHADAKU = GLOBAL_CONFIG.copy(
    id = "Samehadaku",
    name = "Samehadaku",
    mainUrl = "https://samehadaku.biz",
    seriesUrl = null,
    searchUrl = null,
    lang = "id",
    supportedTypes = setOf(TvType.Anime, TvType.AnimeMovie, TvType.OVA),
    searchPathPattern = "{baseUrl}/?s={query}",
    mainPagePathPattern = "{baseUrl}/{data}{page}",
    moviePathSegment = "/movie/",
    tvPathSegment = "/anime/",
    episodeDataUrlPattern = "{url}",
    searchPageLimit = 2,
    reverseEpisodes = true,
    isJsonSearch = false,
    searchJsonRoot = "data",
    searchJsonTitle = "title",
    searchJsonHref = "slug",
    searchJsonPoster = "poster",
    searchJsonPosterPrefix = "",
    searchJsonType = "type",
    useDocumentLarge = false,
    cacheTtlMinutes = 5L,
    isHorizontal = true,
    refererPlayerMode = "current_url",
    iframeSelectors = "iframe",
    globalHeaders = mapOf(
        "User-Agent" to "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        "Accept-Language" to "id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7"
    ),
    mainPageLists = listOf(
        "page/" to "Latest Episodes",
        "anime/?status=&type=TV&order=update&page=" to "TV Latest",
        "anime/?status=&type=TV&order=popular&page=" to "TV Popular",
        "anime/?status=ongoing&type=TV&order=update&page=" to "TV Ongoing",
        "anime/?status=completed&type=TV&order=update&page=" to "TV Completed",
        "anime/?status=&type=&order=popular&page=" to "All Popular",
        "genres/action/page/" to "Action",
        "genres/adventure/page/" to "Adventure",
        "genres/comedy/page/" to "Comedy",
        "genres/drama/page/" to "Drama",
        "genres/fantasy/page/" to "Fantasy",
        "genres/horror/page/" to "Horror",
        "genres/isekai/page/" to "Isekai",
        "genres/romance/page/" to "Romance",
        "genres/sci-fi/page/" to "Sci-Fi",
        "genres/slice-of-life/page/" to "Slice of Life"
    ),
    dubKeyword = "dub",
    ongoingKeyword = "Ongoing",
    episodeKeyword = "Episode",
    seriesKeyword = "Series",
    comingSoonKeywords = "Coming Soon",
    searchItems = "div.bsx, .listupd .bsx, div.animposx",
    searchTitle = "h2, .entry-title a, .title",
    searchHref = "a",
    searchPoster = "div.bsx img, div.animposx img, .content-thumb img",
    searchRating = ".rtng, .score, .rating",
    searchEpText = ".eps span, .epx, .bt span.epx",
    loadTitle = "h1.entry-title, h1.title, .entry-title h1",
    loadPoster = "div.thumb img, .ts-post-image",
    loadBanner = "",
    loadDesc = "div.entry-content p, .description p, div.description",
    loadInfoBox = "div.spe",
    loadTags = "div.genre-info a, .genres a",
    loadRating = "",
    loadStatus = "div.spe span:contains(Status), .spe",
    loadQuality = "",
    loadTrailer = "iframe[src*=\"youtube\"], .trailer a",
    loadRecommend = "div.relat ul li, .relat article, .related-post article",
    episodeItems = "div.lstepsiode ul li, .eplister li",
    episodeHref = "a",
    episodeTitle = "a, .epl-title",
    episodeNum = ".epl-num",
    episodeDesc = "",
    episodeTime = "",
    linkOptions = "option[value]",
    downloadItems = "div#downloadb li",
    actorItems = "",
    actorName = "",
    watchButtons = ".play-button, .watch-now, .btn-watch",
    seasonContainer = ".tvseason, #season-data",
    imdbExternal = "a[href*='imdb.com/title/']",
    tmdbExternal = "a[href*='themoviedb.org/']",
    iframeTag = "iframe",
    followLinkSelector = "",
    seasonDataSelector = "",
    ajaxPlayerUrl = "",
    selectorJsonData = "",
    attrImage = listOf("data-original", "data-src", "data-lazy-src", "data-litespeed-src", "src", "content"),
    attrHref = listOf("href"),
    attrValue = listOf("value", "data-index", "data-id", "data-url", "data-link", "data-litespeed-src"),
    iframeSources = listOf("src", "data-src", "data-link", "data-litespeed-src"),
    hrefCleanRegex = "",
    hrefCleanReplace = "",
    yearSelector = "",
    yearExtractorRegex = "",
)
